layout_spectrum: 0.238423
name: Bohemian Chica
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5
  lightness: 0.2734668
  saturation: 0.4637046
  rhythmicContrast: 0.1095119
  brandColors:
    - '#ABA3BC'
    - '#67879F'
    - '#A16B88'
    - '#DD4B97'
    - '#0009CF'
typography_spectrum: 0.05819775
