collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4462943
  brandStrength: 0.4505908
  lightness: 0.7790989
  brandColors:
    - '#FFFFFF'
    - '#0E110A'
    - '#2D5924'
    - '#8B8B8D'
    - '#F55A49'
  rhythmicContrast: 0.1095119
typography_spectrum: 0.05819775
layout_spectrum: 0.4924812
name: Bohemian Chica
