layout_spectrum: 0.6143327
typography_spectrum: 0.7853589
color:
  lightness: 0.2260152
  brandStrength: 0.4236891
  saturation: 0.4461263
  rhythmicContrast: 0.2614608
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Bohemian Chica
